version: '3.8'
services:
  database:
    image: postgres:13
    container_name: trello-copy
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

